name: AI Stock Agent

on:

  workflow_dispatch:

jobs:

  run-agent:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v4

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"

      - name: Install Packages

        run: |

          pip install requests
          pip install pandas
          pip install akshare

      - name: Run Agent

        run: |

          python monitor.py
          
      - name: Test Market Data
      
        run: |
          python market_data.py

      - name: Send WeCom Message

        env:

          WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}

        run: |

          python send_wecom.py
          
